ooni/netx

cmd/httpclient/main.go, httpx/httpx.go, httpx/httpx_test.go, internal/dialerapi/dialerapi.go, internal/dialerapi/dialerapi_test.go, netx.go, netx_test.go
This is a necessary building block for measuring SNI based
blocking inside a specific network.
Closes #8
=> netx, httpx: implement ForceSpecificSNI

internal/dnsconf/dnsconf.go, internal/dnstransport/dnsoverhttps/dnsoverhttps.go, internal/dnstransport/dnsoverhttps/dnsoverhttps_test.go, internal/godns/godns_test.go
We can implement the full DoH transport without using any specific
structure of netx/httxp, which is great because it allows us to reduce
the coupling with otherwise unrelated parts of the tree.
This is again from-the-yak-shaving dept.
=> dnsoverhttps.go: decouple from netx/httpx

DESIGN.md, internal/dnsconf/dnsconf.go, internal/dnsconf/dnsconf_test.go, internal/dnstransport/dnsovertcp/dnsovertcp.go, internal/dnstransport/dnsovertcp/dnsovertcp_test.go, internal/dnstransport/dnsoverudp/dnsoverudp.go, internal/dnstransport/dnsoverudp/dnsoverudp_test.go, internal/oodns/oodns_test.go
Same purpose of #28 and #27. We want to reach a situation where we can
construct a DNS transport that does not depend on netx/httpx.
The general objective here is (1) to decouple unrelated parts of the
tree and (2) to use dependency injection to enable writing wrappers for
any piece of code, so to enable follow-up measurements when any step
we're performing seems to return something fishy.
While working on this diff, I noticed that there was inconsistency
in the way in which we manage DNS:
- some resolvers tolerated domain input, others did not
- some resolvers automatically added ports in some cases
I've therefore made sure all resolvers are constructed in a way that
is robust to supplying DNS names as well as to missing ports.
=> dnsovertcp: decouple from netx/httpx

dnsx/dnsx.go, internal/dnstransport/dnsoverhttps/dnsoverhttps.go, internal/dnstransport/dnsoverhttps/dnsoverhttps_test.go, internal/dnstransport/dnsovertcp/dnsovertcp.go, internal/dnstransport/dnsovertcp/dnsovertcp_test.go, internal/dnstransport/dnsoverudp/dnsoverudp.go, internal/dnstransport/dnsoverudp/dnsoverudp_test.go, internal/godns/godns.go, internal/oodns/oodns.go
This is required to pass along cancellation information, where this
is possible, as well as information on what we're doing.
=> [API CHANGE] Pass context to dns RoundTripper

cmd/dnsclient/main.go, dnsx/dnsx.go, internal/dnsconf/dnsconf.go, internal/dnstransport/dnsoverhttps/dnsoverhttps.go, internal/dnstransport/dnsovertcp/dnsovertcp.go, internal/dnstransport/dnsoverudp/dnsoverudp.go, internal/godns/godns.go, internal/oodns/oodns.go, internal/oodns/oodns_test.go, model/model.go, netx.go
Keep dnsx because it's the API. Yet, move to save import headaches
and just have aliases in dsnx.
=> Move relevant DNS interfaces in model

internal/dnstransport/dnsovertcp/dnsovertcp.go, internal/dnstransport/dnsovertcp/dnsovertcp_test.go
=> dnsovertcp: don't expose internals

DESIGN.md, internal/connid/connid.go, internal/connid/connid_test.go, internal/dialer/dialerbase/dialerbase.go, internal/dialer/dialerbase/dialerbase_test.go, internal/dialer/dnsdialer/dnsdialer.go, internal/dialer/tlsdialer/tlsdialer_test.go, internal/httptransport/tracetripper/tracetripper.go, model/model.go
We are using the local port and the protocol. This makes it
possible to join HTTP and network level measurements.
=> Use ConnID that we can generate from HTTP

DESIGN.md, internal/httptransport/bodyreader/bodyreader.go, internal/httptransport/tracetripper/tracetripper.go, model/model.go
The round trip is what happens since we start thinking about
sending a request until when we receive response.
This is a clearly defined operation with a well defined result
indicating error or HTTP response headers.
As such, emit its events in the proper model, and make sure
that we also emit the error that occurred (if any).
This change simplifies data analysis.
While there, stop duplicating docs in the design document, since
we are going to change events more times in the future.
=> [DATA CHANGE] Clearly identify the round trip

internal/dialer/tlsdialer/tlsdialer.go, internal/httptransport/tracetripper/tracetripper.go, internal/internal.go, model/model.go
I'm starting to think it would be better to pass the handler
through a context, and to have a unique measuring server used
by the app, rather than creating one each time.
This means that, in turn, we'll have context rooted measurements.
=> [DATA CHANGE] let net/http perform TLS handshake

internal/dialer/dialer.go, internal/dialer/dialer_test.go, internal/dialer/dnsdialer/dnsdialer.go, internal/dialer/dnsdialer/dnsdialer_test.go, internal/dialer/tlsdialer/tlsdialer.go, internal/dialer/tlsdialer/tlsdialer_test.go, internal/httptransport/bodyreader/bodyreader.go, internal/httptransport/bodyreader/bodyreader_test.go, internal/httptransport/httptransport.go, internal/httptransport/httptransport_test.go, internal/httptransport/tracetripper/tracetripper.go, internal/httptransport/tracetripper/tracetripper_test.go, internal/internal.go, internal/internal_test.go, internal/resolver/ooniresolver/ooniresolver.go, internal/resolver/ooniresolver/ooniresolver_test.go, internal/resolver/resolver.go, internal/resolver/resolver_test.go, model/model.go, model/model_test.go
No hurry to do that externally, for now. Paves the way for
doing that quite easily, however.
=> internal: make measurements context rooted

internal/dialer/dnsdialer/dnsdialer.go, model/model.go
Lots of stuff may happen between the beginning and the end of a
resolver, therefore, it makes sense to split.
=> [DATA CHANGE] Split the resolve event

internal/httptransport/tracetripper/tracetripper.go, model/model.go
This is useful to distinguish the case where the error was in
sending the request from the one where it was instead in receiving
the response. It is a small aspect, but still useful.
=> [DATA CHANGE] HTTPRequestDone: add error

handlers/logger/logger.go, internal/dialer/dnsdialer/dnsdialer.go, internal/dialid/dialid.go, internal/dialid/dialid_test.go, internal/httptransport/bodyreader/bodyreader.go, internal/httptransport/tracetripper/tracetripper.go, internal/httptransport/transactioner/transactioner.go, internal/httptransport/transactioner/transactioner_test.go, internal/transactionid/transactionid.go, internal/transactionid/transactionid_test.go, model/model.go
1. make sure that, when we start a DoH transaction to resolve a
domain name, we know which dial originated it.
2. make sure that, when we dial, we always know what is the
transaction that triggered us, if any (otherwise, ID == zero).
3. while there, always emit resolve, also for IP addresses, so
we have a place where to store the origin transactionID for the
common case like `udp://8.8.8.8:53`. This solution has been
preferred to introducing another event.
=> Cross reference dials and transactions

handlers/logger/logger.go, internal/dialer/dialerbase/dialerbase.go, internal/dialer/dnsdialer/dnsdialer.go, model/model.go
After trial and error, I have determined that, in general, to decide
whether we need follow-up measurements, we need just the result of
four events in the HTTP round trip:
- RESOLVE_DONE
- CONNECT
- HANDSHAKE_DONE
- ROUND_TRIP_DONE
In some cases it may be possible to run operations inline while in
others it's probably best to run concurrently or later.
Regardless of the implementation strategy, this diff makes sure that
by combining this four events only, we have enough information to
conclude whether to trigger more measurements.
This conclusion is based on my analysis using ooni/jafar, it may be
of course that later we'll need to tweak this a bit.
I've been doing refactoring for quite some time to prepare this.
Master issue: https://github.com/ooni/probe-engine/issues/87
=> Make events actionable for OONI's nervous system

internal/dialer/dnsdialer/dnsdialer.go, internal/dialer/dnsdialer/dnsdialer_test.go, model/model.go
A MeasurementRoot can contain an alternative LookupHost function
which may be used to bypass the usual chain.
This is also functional to the OONI reactive system.
See https://github.com/ooni/probe-engine/issues/87
=> dnsdialer: allow to divert lookuphost

cmd/httpclient/main.go, handlers/logger/logger.go, handlers/logger/logger_test.go, model/model.go, x/nervousresolver/bogon/bogon.go, x/nervousresolver/bogon/bogon_test.go, x/nervousresolver/nervousresolver.go, x/nervousresolver/nervousresolver_test.go
I am not 100% sold yet on what is the actionable top-level event
to in order to clarify in the log we've seen a bogon.
Another good actionable idea could be to flag the presence of
bogons (maybe along with DialID?) in MeasurementRoot, but this
is also something I'd like to think about.
This code in here is good for me to start understand it and then
applying further changes as I get more insights.
Master ticket is https://github.com/ooni/probe-engine/issues/87
=> Nervous system: nervous resolver that handles bogons

cmd/httpclient/main.go, model/model.go, x/nervousresolver/nervousresolver.go, x/scoreboard/scoreboard.go, x/scoreboard/scoreboard_test.go
Implement a scoreboard and write there what we see. The follow up
action may or may not be required.
This is also functional to the OONI reactive system.
See ooni/probe-engine#87
=> Make nervous system data more immediately actionable

internal/httptransport/tracetripper/tracetripper.go, x/nervousresolver/nervousresolver.go, x/scoreboard/scoreboard.go, x/scoreboard/scoreboard_test.go
The scoreboard package will probably benefit from some more
precise unit testing with respect to returned keys.
Work related to ooni/probe-engine#87
=> Extend scoreboard to also track TLS handshake RST

x/nervousresolver/nervousresolver.go, x/nervousresolver/nervousresolver_test.go
For now let us limit to act if we see any bogon. If we see at
least one, we cannot trust the upstream DNS. If we don't see any,
or we see an error, for now don't use the secondary resolver as
this complicates making other techniques possible.
I believe we may reconsider the latter choice when we have
some more experience with this part of the tree and we have
run more testing with jafar and/or in the field.
=> nervousresolver: fix processing of bogons

DESIGN.md, cmd/httpclient/main.go, cmd/httpclient/main_test.go, httpx/httpx.go, httpx/httpx_test.go, internal/internal.go, internal/internal_test.go, netx.go, netx_test.go, x/nervousresolver/nervousresolver.go, x/nervousresolver/nervousresolver_test.go, x/porcelain/porcelain.go
I realised it was not a good idea to have it hidden and enabled
by default, as it prevented other kind of testing.
So, allow using it as opt-in.
Also, while there, make it better by using it whenever we fail
to query the DNS so to have more DNS robustness.
I think with this I'm near the bottom of my netx TODO list.
=> Rework nervous resolver and make it opt-in

internal/httptransport/httptransport.go, internal/internal.go
We need to observe real headers, so reduce the magic performed
under the hood by Go. The really good thing would be to be able
to store information about the round trip more easily.
Events are great for debugging, but some higher level abstraction
that takes into account all oddities is probably required.
=> Adapt the HTTP configuration more to OONI needs

internal/httptransport/tracetripper/tracetripper.go, internal/httptransport/tracetripper/tracetripper_test.go, model/model.go, x/logger/logger.go
This diff implements easy handling of round trips by putting into
the same event all the information we may possibly need.
The only missing bit of information is the body of the final
request, which however can be read by other means.
=> http: implement easy handling of round trips

cmd/httpclient/main.go, x/porcelain/porcelain.go, x/porcelain/porcelain_test.go
I've determined that it's better to add more porcelain here as
an extension, and keep ooni/probe-engine simpler.
Because, if something breaks in the data format, we want to catch
it inside here rather than cathing it in the other repo.
So, ooni/probe-engine will use the porcelain that I've just
added to run telegram and will process results, that are now
in a format by which processing is very easy.
Basically, ooni/probe-engine will just need to filter out some
bits of information it doesn't need and call .Error() for errors.
Note that the porcelain I'm adding here is also enough to
implement web_connectivity's core and possible other experiments.
Reference issue: https://github.com/ooni/probe-engine/issues/86
=> Add enough porcelain to make Telegram simple

x/nervousresolver/nervousresolver.go
We should probably introduce a longer chain of fallbacks in the
nervous resolver, but, for now, using the IP address is good enough
because it can protect us against the whole DNS being down.
This happened to me in Italy, when "Vodafone rete sicura" had
several hours of outage and the default DNS was not working as
intended, while there was IP connectivity.
Reference issue: https://github.com/ooni/probe-engine/issues/88
=> nervousresolver: use cloudflare IP address

internal/dialer/dnsdialer/dnsdialer.go, internal/dialer/dnsdialer/dnsdialer_test.go
There is no actual resolve of IPs. We include the TxID also in
the connect event, so there's actually no need for emitting a
resolve event with the IP. There was need for that before we had
the TxID inside of connect, but now we're good.
=> dialer: no need to emit "resolve" of IPs

internal/dialer/dnsdialer/dnsdialer.go, internal/internal.go, internal/resolver/emitterresolver/emitterresolver.go, internal/resolver/emitterresolver/emitterresolver_test.go, internal/resolver/resolver.go
This fixes a bug where a standalone Resolver would not emit
the final result of its resolve, because there is no dial
attached to the resolve itself. Also, from a logic standpoint,
it seems anyway better to emit such event there.
=> internal: let the resolver emit resolve events

internal/internal.go
We were creating a system resolver that was not correctly wrapped
using the emittingresolver, hence we didn't see events.
=> fix(internal.go): make sure system resolver emits events

internal/httptransport/bodytracer/bodytracer.go, internal/httptransport/bodytracer/bodytracer_test.go, internal/httptransport/httptransport.go, internal/httptransport/tracetripper/tracetripper.go, internal/httptransport/tracetripper/tracetripper_test.go, model/model.go, x/logger/logger.go, x/porcelain/porcelain.go
Always read snapshots of all bodies. Limit snapshot to 1<<17
that is good enough because:
1. for requests, we can always save them since we issue them but
it may be useful to save small requests
2. for responses, we can always save them except redirects and
DoH, and in both cases we are talking about small bodies
Fixes the output emitted by a DoH query.
We can now probably further simplify porcelain.go in a followup PR.
=> http: change body reading strategy

internal/errwrapper/errwrapper.go, internal/errwrapper/errwrapper_test.go, internal/resolver/ooniresolver/ooniresolver.go, internal/resolver/ooniresolver/ooniresolver_test.go, model/model.go, x/porcelain/porcelain.go, x/porcelain/porcelain_test.go
* errwrapper: map the TLS handshake timeout error
* ooniresolver: correctly recognize and handle NXDOMAIN in ooniresolver
* XSNIBlockingFollowup: better naming for resolve results, which
are clearly more coarse grained than just "queries"
Xref: https://github.com/ooni/probe-engine/issues/87
=> Fix several DNS issues when testing with jafar

internal/internal.go, internal/internal_test.go, x/porcelain/porcelain.go
As explained in the code, this allows us to avoid worrying about
closing the connections that an interim HTTP client may have
opened, saving lots of API complexity. Because setting NoHandler
as the handler is really the common case, this is a good enough
not-so-complex solution to avoid the technical debt caused by
failing to close the open connections of an *http.Client.
=> internal: use global doh client with NoHandler

httpx/httpx.go, internal/internal.go, internal/internal_test.go
Complement the previous path by forcing no keepalives if the
user requests doh with a handler.
This reduces the technical debt entailed by DoH to zero.
=> internal: no keepalive if doh with handler

internal/resolver/ooniresolver/ooniresolver.go
The first error is the one that is most likely to be caused by the network. Subsequent errors are more likely to be caused by context deadlines. So, the first error is attached to an operation, while subsequent errors may possibly not be. If so, the resulting failing operation is not correct.
=> roundTripQuery: trust the first error more

DESIGN.md, httpx/httpx.go, httpx/httpx_test.go, internal/internal.go, internal/internal_test.go, x/porcelain/porcelain.go
Related to #9 but implemented differently.
=> Make sure clients for measurements don't use proxy

DESIGN.md, httpx/httpx.go, httpx/httpx_test.go, netx.go, netx_test.go
No real API change. What changes is the way in which I think
about next, so updated the document to reflect that.
While there, define a bunch of more tidy APIs where we can
avoid passing in handlers.NoHandler explicitly.
Also, the real replacement is the transport and not the client
which is just syntactic sugar around it. Make it clear.
=> DESIGN.md: simplify and reorganize after recent changes

internal/httptransport/tracetripper/tracetripper.go, internal/httptransport/tracetripper/tracetripper_test.go, modelx/modelx.go, x/logger/logger.go, x/porcelain/porcelain.go, x/porcelain/porcelain_test.go
If the user explicitly requests for unbounded bodies, then satisfy
this request, but from now on, the default is snapped at 1<<20.
Should address all OONI needs and be safer.
=> http: always enforce a body snap size

README.md
The main reason why I opened this PR was to understand why we have five checks rather than three, and specifically two duplicate Travis checks. The reason is the one explained in https://github.com/travis-ci/travis-ci/issues/10152#issuecomment-424703023, and the fix is to go to https://travis-ci.org/organizations/ooni/repositories and manually disable netx.
That said, I also like the new wording slightly more.
=> README.md: slightly change the wording

internal/dialer/tlsdialer/tlsdialer.go, modelx/modelx.go, x/logger/logger.go
This helps with analysing tests for SNI triggered RST injection.
=> model: publish SNI when we force it being different

internal/errwrapper/errwrapper.go, internal/errwrapper/errwrapper_test.go, internal/httptransport/tracetripper/tracetripper.go, internal/resolver/parentresolver/parentresolver.go, internal/resolver/parentresolver/parentresolver_test.go, internal/resolver/resolver_test.go, modelx/modelx.go, x/logger/logger.go, x/logger/logger_test.go, x/porcelain/porcelain.go, x/porcelain/porcelain_test.go
This PR contains three small patches from my development branch:
1. disable auto-followup for bogons, as it may be problematic in some corner cases
2. support Accept and Accept-Language headers
3. emit cURL like logs because people is used to them (including me)
=> cURL like logs, support Accept{,-Language}, disable auto-followup for bogons

x/logger/logger.go
It's more flexible to depend on an apex/log like interface.
=> x/logger: don't explicitly depend on apex/log

internal/resolver/ooniresolver/ooniresolver_test.go, x/porcelain/porcelain_test.go
Prompted by failures in #144. While there, mention with documentation which tests are gonna fail if you are using DNS hijacking ISP settings like Vodafone Italia does by default.
=> Make sure regress tests are all green on travis

DESIGN.md, go.mod, internal/httptransport/tracetripper/tracetripper.go, internal/httptransport/tracetripper/tracetripper_test.go, internal/internal.go, internal/internal_test.go, modelx/modelx.go, modelx/modelx_test.go, x/logger/logger.go, x/porcelain/porcelain.go, x/porcelain/porcelain_test.go, x/scoreboard/scoreboard.go
This is yak shaving as part of https://github.com/ooni/probe-engine/issues/2. Specifically, this diff refactors the code such that `netx/x/{logger,porcelain}` does not depend on `netx/internal`.
Each individual commit contains its own short rationale.
On a broader level, this diff is related to discussions I had with @FedericoCeratto concerning unifying `netx` and `probe-engine` to reduce complexity. I have determined that this won't happen because:
1. I am using `netx` also in `jafar` and it makes sense therefore to keep `netx` independent
2. the `netx` API described in `DESIGN.md` is not poised to change because it is based on the standard library API, hence we should keep it stable
Thus, I can see how occasionally we'll make the data model richer, or apply fixes, but I see low coupling …
=> Detach porcelain from netx/internal

DESIGN.md, cmd/httpdo/main.go, httpx/httpx.go, httpx/httpx_test.go, internal/internal.go, internal/internal_test.go, netx.go, netx_test.go, x/logger/logger.go, x/porcelain/porcelain.go, x/porcelain/porcelain_test.go
Closes #127. Related to https://github.com/ooni/probe-engine/issues/2.
=> netx: allow skipping certificate verification
